### ISSUE TITLE
[Bug] Facebook removed fields from all versions of the API

### ISSUE THREAD

**Issue by awoehrl** [fivetran/dbt_facebook_pages_source#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Facebook removed a numver of fields from their API on March 14th 2024. Some are used in the package as well.

https://developers.facebook.com/docs/graph-api/changelog/non-versioned-changes/nvc-2023

**Removed metrics:**
page_actions_post_reactions_anger_total
page_actions_post_reactions_haha_total
page_actions_post_reactions_like_total
page_actions_post_reactions_love_total
page_actions_post_reactions_sorry_total
page_actions_post_reactions_total
page_actions_post_reactions_wow_total
page_call_phone_clicks_by_age_gender_logged_in_unique
page_call_phone_clicks_by_site_logged_in_unique
page_call_phone_clicks_logged_in_by_city_unique
page_call_phone_clicks_logged_in_by_country_unique
page_call_phone_clicks_logged_in_by_locale_unique
page_consumptions
page_content_activity
page_content_activity_by_action_type
page_content_activity_by_action_type_unique
page_content_activity_by_age_gender_unique
page_content_activity_by_city_unique
page_content_activity_by_country_unique
page_content_activity_by_locale_unique
page_content_activity_unique
page_cta_clicks_by_age_gender_logged_in_unique
page_cta_clicks_by_site_logged_in_unique
page_cta_clicks_logged_in_by_city_unique
page_cta_clicks_logged_in_by_country_unique
page_cta_clicks_logged_in_by_locale_unique
page_daily_follows_by_source_unique
page_daily_unfollows_by_source_unique
page_engaged_users
page_fans_by_like_source_unique
page_fans_by_like_source
page_fans_by_unlike_source_unique
page_fans_by_unlike_source
page_fans_gender_age
page_follows_city
page_follows_country
page_follows_gender_age
page_follows_locale
page_get_directions_clicks_by_age_gender_logged_in_unique
page_get_directions_clicks_by_site_logged_in_unique
page_get_directions_clicks_logged_in_by_city_unique
page_get_directions_clicks_logged_in_by_country_unique
page_impressions_frequency_distribution
page_places_checkin_mobile_unique
page_places_checkin_mobile
page_places_checkins_by_age_gender
page_places_checkins_by_city
page_places_checkins_by_country
page_places_checkins_by_locale
page_positive_feedback_by_type_unique
page_positive_feedback_by_type
page_positive_feedback_unique
page_positive_feedback
page_posts_impressions_frequency_distribution
page_views_by_age_gender_logged_in_unique
page_views_by_city_logged_in_unique
page_views_by_country_logged_in_unique
page_views_by_internal_referer_logged_in_unique
page_views_by_locale_logged_in_unique
page_views_by_profile_tab_logged_in_unique
page_views_by_profile_tab_total
page_views_by_referers_logged_in_unique
page_views_by_site_logged_in_unique
page_views_external_referrals
page_views_logged_in_total
page_views_logged_in_unique
page_views_login_unique
page_views_login
page_views_logout
page_website_clicks_by_age_gender_logged_in_unique
page_website_clicks_by_site_logged_in_unique
page_website_clicks_logged_in_by_city_unique
page_website_clicks_logged_in_by_country_unique
page_website_clicks_logged_in_by_locale_unique
post_activity
post_activity_by_action_type
post_activity_by_action_type_unique
post_activity_unique
post_impressions_fan_paid_unique*
post_impressions_fan_paid*

### Relevant error log or model output

```shell
-
```

### Expected behavior

Model data based on latest version of the API and have logic for working with old data.

### dbt Project configurations

-

### Package versions

latest

### What database are you using dbt with?

bigquery

### dbt Version

latest

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-reneeli** [comment]
Thanks @awoehrl  for letting us know of these deprecations! We will remove these from our models in the coming weeks.

**Comment by fivetran-catfritz** [comment]
Hi @awoehrl to update you, I will be working on this issue in the next week or so. I noticed that since the time this issue was opened, the `page_actions_post_reactions_*` fields were restored, so we will keep those but address the rest of the mentioned fields. We'll keep you posted!

**Comment by fivetran-catfritz** [comment]
Hi @awoehrl the latest updates have been released in v0.3.0!
